apiVersion: v2
name: k-view
description: A modern, lightweight Kubernetes dashboard with Google SSO and declarative RBAC.
type: application
version: 0.46.0
appVersion: "0.46.0"
icon: https://raw.githubusercontent.com/oisis/k-view/main/web/src/assets/k-view-logo.png
keywords:
  - kubernetes
  - dashboard
  - rbac
  - oidc
  - sso
home: https://github.com/oisis/k-view
sources:
  - https://github.com/oisis/k-view
maintainers:
  - name: oisis
    email: oisis@k-view.io
