{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k-view.fullname" . }}-rbac-config
  labels:
    {{- include "k-view.labels" . | nindent 4 }}
data:
  assignments.yaml: |
    assignments:
{{- range .Values.rbac.assignments }}
{{- $role := .role }}
{{- $ns := .namespace }}
{{- if .user }}
  {{- if kindIs "slice" .user }}
    {{- range .user }}
      - user: {{ . | quote }}
        role: {{ $role | quote }}
      {{- if $ns }}
        namespace: {{ $ns | quote }}
      {{- end }}
    {{- end }}
  {{- else }}
      - user: {{ .user | quote }}
        role: {{ $role | quote }}
    {{- if $ns }}
        namespace: {{ $ns | quote }}
    {{- end }}
  {{- end }}
{{- else if .group }}
  {{- if kindIs "slice" .group }}
    {{- range .group }}
      - group: {{ . | quote }}
        role: {{ $role | quote }}
      {{- if $ns }}
        namespace: {{ $ns | quote }}
      {{- end }}
    {{- end }}
  {{- else }}
      - group: {{ .group | quote }}
        role: {{ $role | quote }}
    {{- if $ns }}
        namespace: {{ $ns | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- range .Values.localUsers }}
{{- if .role }}
      - user: {{ .username | quote }}
        role: {{ .role | quote }}
{{- if .namespace }}
        namespace: {{ .namespace | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
