{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k-view.fullname" . }}-rbac-config
  labels:
    {{- include "k-view.labels" . | nindent 4 }}
data:
  assignments.yaml: |
    assignments:
{{- range .Values.assignments }}
{{- $role := .role }}
{{- $ns := .namespace }}
{{- if .user }}
  {{- $current := .user }}
  {{- if typeIs "string" $current }}
      - user: {{ $current | quote }}
        role: {{ $role | quote }}
    {{- if $ns }}
        namespace: {{ $ns | quote }}
    {{- end }}
  {{- else }}
    {{- range $current }}
      - user: {{ . | quote }}
        role: {{ $role | quote }}
      {{- if $ns }}
        namespace: {{ $ns | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- else if .group }}
  {{- $current := .group }}
  {{- if typeIs "string" $current }}
      - group: {{ $current | quote }}
        role: {{ $role | quote }}
    {{- if $ns }}
        namespace: {{ $ns | quote }}
    {{- end }}
  {{- else }}
    {{- range $current }}
      - group: {{ . | quote }}
        role: {{ $role | quote }}
      {{- if $ns }}
        namespace: {{ $ns | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- range .Values.localUsers }}
{{- if .role }}
      - user: {{ .username | quote }}
        role: {{ .role | quote }}
{{- if .namespace }}
        namespace: {{ .namespace | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
