apiVersion: v1
kind: Secret
metadata:
  name: test-sa-secret
  namespace: k-view-test-data
type: Opaque
data:
  token: dGVzdC10b2tlbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: test-pull-secret
  namespace: k-view-test-data
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0Ijp7ImF1dGgiOiJkR1Z6ZEhNdGJHOXpZVzVrIn19fQ==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-k-view-serviceaccount
  namespace: k-view-test-data
  labels:
    app: test-k-view
    tier: security
  annotations:
    k-view.io/description: "Dedicated account for test suite application pods"
secrets:
- name: test-sa-secret
imagePullSecrets:
- name: test-pull-secret
