apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-k-view-resourcequota
  namespace: k-view-test-data
  labels:
    app: k-view-test
spec:
  hard:
    requests.cpu: 4
    requests.memory: 8Gi
    limits.cpu: 16
    limits.memory: 16Gi
    pods: 20
    services: 10
