apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-k-view-rolebinding
  namespace: k-view-test-data
  labels:
    app: test-k-view
    tier: security
  annotations:
    k-view.io/description: "Binding for application roles"
    k-view.io/last-review: "2026-03-02"
subjects:
- kind: ServiceAccount
  name: test-k-view-serviceaccount
  namespace: k-view-test-data
roleRef:
  kind: Role
  name: test-k-view-role
  apiGroup: rbac.authorization.k8s.io
