apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testviewresources.k-view.local
spec:
  group: k-view.local
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
  scope: Namespaced
  names:
    plural: testviewresources
    singular: testviewresource
    kind: TestViewResource
    shortNames:
    - tvr
