apiVersion: v1
kind: Event
metadata:
  name: test-k-view-event
  namespace: k-view-test-data
involvedObject:
  kind: Pod
  name: test-k-view-pod
  namespace: k-view-test-data
reason: TestReason
message: "This is a manually created test event for K-View"
type: Normal
firstTimestamp: "2024-01-01T00:00:00Z"
lastTimestamp: "2024-01-01T00:00:00Z"
count: 1
source:
  component: k-view-test-suite
