apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-k-view-serviceaccount
  namespace: k-view-test-data
  labels:
    app: test-k-view
    tier: security
    scope: internal
  annotations:
    k-view.io/description: "Dedicated account for test suite application pods"
    k-view.io/permissions: "pod-reader"
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/k-view-test-role"

