apiVersion: v1
kind: LimitRange
metadata:
  name: test-k-view-limitrange
  namespace: k-view-test-data
  labels:
    app: k-view-test
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
