apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-k-view-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
  storageClassName: test-k-view-storageclass
