apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-k-view-pvc
  namespace: k-view-test-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: test-k-view-storageclass
