apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-k-view-ingress
  namespace: k-view-test-data
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: test.k-view.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-k-view-service
            port:
              number: 80
