apiVersion: v1
kind: Service
metadata:
  name: test-k-view-service
  namespace: k-view-test-data
spec:
  selector:
    app: test-k-view-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
