apiVersion: v1
kind: Secret
metadata:
  name: test-k-view-secret
  namespace: k-view-test-data
  labels:
    app: test-k-view
    type: credentials
type: Opaque
data:
  api-key: dGVzdC1zZWNyZXQta2V5LXZhbHVl
  password: cGFzc3dvcmQxMjM=
