import {
    LayoutDashboard, Server, Terminal, LogOut, FlaskConical, ShieldAlert,
    Boxes, Package, GitBranch, RefreshCw, Clock, Network, Globe,
    FileText, Lock, Database, Puzzle, ChevronDown, ChevronRight,
    Shield, Key, User, Users, Link, AlertTriangle, Globe2, Activity,
    Settings as SettingsIcon, Moon, Sun, Palette, Info, PanelLeftClose, PanelLeftOpen,
    Layers, Repeat, ShieldCheck, Plus, Zap, Heart, Search, X, AlertCircle, ExternalLink, Edit3, Download,
    ChevronLeft, Check, Fingerprint, List, Languages, Cpu, Hash, Box, MemoryStick, CheckCircle,
    XCircle, MoreVertical, ChevronUp, ArrowUpDown, Clipboard, CheckCircle2, ChevronsLeft, ChevronsRight, Trash2,
    ShieldOff, HardDrive, Layout, FileCode2, SquareCode
} from 'lucide-react';

const commonIcons = {
    dashboard: LayoutDashboard,
    nodes: Server,
    console: Terminal,
    about: Info,
    settings: SettingsIcon,
    logout: LogOut,
    admin_panel: ShieldAlert,
    expand_menu: PanelLeftOpen,
    collapse_menu: PanelLeftClose,
    chevron_down: ChevronDown,
    chevron_up: ChevronUp,
    chevron_right: ChevronRight,
    chevron_left: ChevronLeft,
    chevrons_left: ChevronsLeft,
    chevrons_right: ChevronsRight,
    plus: Plus,
    zap: Zap,
    heart: Heart,
    search: Search,
    close: X,
    alert: AlertCircle,
    alert_triangle: AlertTriangle,
    external_link: ExternalLink,
    edit: Edit3,
    download: Download,
    refresh: RefreshCw,
    activity: Activity,
    palette: Palette,
    sun: Sun,
    moon: Moon,
    check: Check,
    fingerprint: Fingerprint,
    list: List,
    languages: Languages,
    cpu: Cpu,
    hash: Hash,
    box: Box,
    terminal: Terminal,
    memory: MemoryStick,
    check_circle: CheckCircle,
    check_circle_alt: CheckCircle2,
    x_circle: XCircle,
    more: MoreVertical,
    sort: ArrowUpDown,
    clipboard: Clipboard,
    clock: Clock,
    manifest: FileText,
    trash: Trash2,
    shield: Shield,
    lock: Lock,
    globe: Globe,
    database: Database,
    puzzle: Puzzle,
    users: Users,
    link: Link,
    layout: Layout,
    file_code: FileCode2,
    shield_off: ShieldOff,
    hard_drive: HardDrive,
    user: User,
    layers: Layers,
    shield_check: ShieldCheck,

    // Resource types
    cronjob: Clock,
    daemonset: RefreshCw,
    deployment: Package,
    job: Database,
    pod: Boxes,
    replicaset: Layers,
    replicationcontroller: Repeat,
    statefulset: GitBranch,
    ingressclass: Globe,
    ingress: Globe,
    service: Network,
    configmap: FileText,
    pvc: Database,
    secret: Lock,
    storageclass: Database,
    clusterrolebinding: Link,
    clusterrole: Shield,
    crd: Puzzle,
    event: Activity,
    namespace: Globe2,
    networkpolicy: AlertTriangle,
    pv: Database,
    rolebinding: Link,
    role: Key,
    serviceaccount: Users
};

export default {
    id: 'k-view',
    name: 'K-view',
    author: 'OiSiS',
    themes: {
        dark: {
            name: 'K-view',
            variables: {
                '--bg-main': 'rgba(11, 15, 25, 0.8)',
                '--bg-sidebar': '#0F172A',
                '--bg-card': 'rgba(17, 24, 39, 0.7)',
                '--bg-card-hover': '#1E293B',
                '--bg-muted': '#111827',
                '--border-color': '#334155',
                '--border-muted': '#111827',
                '--text-primary': '#F9FAFB',
                '--text-white': '#FFFFFF',
                '--text-secondary': '#94A3B8',
                '--text-muted': '#64748B',
                '--sidebar-hover': '#1E293B',
                '--bg-input': '#1e293b',
                '--text-input': '#ffffff',
                '--accent': '#6366F1',
                '--accent-hover': '#4F46E5',
                '--bg-console': '#020617',
                '--bg-editor': '#0D1117',
                '--bg-glass': 'rgba(15, 23, 42, 0.4)',
                '--bg-glass-deep': 'rgba(15, 23, 42, 0.7)',
                '--bg-dropdown': '#111827',
                '--text-editor-code': '#93C5FD',
                '--wallpaper-opacity': '0.12',
                '--wallpaper-grayscale': '100%',
                '--wallpaper-brightness': '0.5',
                '--text-success': '#4ADE80',
                '--text-error': '#F87171',
                '--text-warning': '#FBBF24',
                '--text-info': '#60A5FA',
                '--text-purple': '#A78BFA',
                '--text-orange': '#FB923C',
                '--text-cyan': '#22D3EE'
            }
        }
    },
    icons: commonIcons
};
