import {
    LayoutDashboard, Server, Terminal, LogOut, FlaskConical, ShieldAlert,
    Boxes, Package, GitBranch, RefreshCw, Clock, Network, Globe,
    FileText, Lock, Database, Puzzle, ChevronDown, ChevronRight,
    Shield, Key, User, Users, Link, AlertTriangle, Globe2, Activity,
    Settings as SettingsIcon, Moon, Sun, Palette, Info, PanelLeftClose, PanelLeftOpen,
    Layers, Repeat, ShieldCheck, Plus, Zap, Heart, Search, X, AlertCircle, ExternalLink, Edit3, Download,
    ChevronLeft, Check, Fingerprint, List, Languages, Cpu, Hash, Box, MemoryStick, CheckCircle,
    XCircle, MoreVertical, ChevronUp, ArrowUpDown, Clipboard, CheckCircle2, ChevronsLeft, ChevronsRight, Trash2,
    ShieldOff, HardDrive, Layout, FileCode2, SquareCode
} from 'lucide-react';

const commonIcons = {
    dashboard: LayoutDashboard,
    nodes: Server,
    console: Terminal,
    about: Info,
    settings: SettingsIcon,
    logout: LogOut,
    admin_panel: ShieldAlert,
    expand_menu: PanelLeftOpen,
    collapse_menu: PanelLeftClose,
    chevron_down: ChevronDown,
    chevron_up: ChevronUp,
    chevron_right: ChevronRight,
    chevron_left: ChevronLeft,
    chevrons_left: ChevronsLeft,
    chevrons_right: ChevronsRight,
    plus: Plus,
    zap: Zap,
    heart: Heart,
    search: Search,
    close: X,
    alert: AlertCircle,
    alert_triangle: AlertTriangle,
    external_link: ExternalLink,
    edit: Edit3,
    download: Download,
    refresh: RefreshCw,
    activity: Activity,
    palette: Palette,
    sun: Sun,
    moon: Moon,
    check: Check,
    fingerprint: Fingerprint,
    list: List,
    languages: Languages,
    cpu: Cpu,
    hash: Hash,
    box: Box,
    terminal: Terminal,
    memory: MemoryStick,
    check_circle: CheckCircle,
    check_circle_alt: CheckCircle2,
    x_circle: XCircle,
    more: MoreVertical,
    sort: ArrowUpDown,
    clipboard: Clipboard,
    clock: Clock,
    manifest: FileText,
    trash: Trash2,
    shield: Shield,
    lock: Lock,
    globe: Globe,
    database: Database,
    puzzle: Puzzle,
    users: Users,
    link: Link,
    layout: Layout,
    file_code: FileCode2,
    shield_off: ShieldOff,
    hard_drive: HardDrive,
    user: User,
    layers: Layers,
    shield_check: ShieldCheck,

    // Resource types
    cronjob: Clock,
    daemonset: RefreshCw,
    deployment: Package,
    job: Database,
    pod: Boxes,
    replicaset: Layers,
    replicationcontroller: Repeat,
    statefulset: GitBranch,
    ingressclass: Globe,
    ingress: Globe,
    service: Network,
    configmap: FileText,
    pvc: Database,
    secret: Lock,
    storageclass: Database,
    clusterrolebinding: Link,
    clusterrole: Shield,
    crd: Puzzle,
    event: Activity,
    namespace: Globe2,
    networkpolicy: AlertTriangle,
    pv: Database,
    rolebinding: Link,
    role: Key,
    serviceaccount: Users
};

export default {
    id: 'light',
    name: 'Light',
    author: 'Oisis',
    themes: {
        light: {
            name: 'Crisp Light',
            variables: {
                '--bg-main': '#ffffff',
                '--bg-sidebar': '#f1f5f9',
                '--bg-card': '#ffffff',
                '--bg-card-hover': '#f8fafc',
                '--bg-muted': '#f1f5f9',
                '--bg-glass': 'rgba(255, 255, 255, 0.9)',
                '--bg-glass-deep': 'rgba(255, 255, 255, 0.95)',
                '--bg-dropdown': '#ffffff',
                '--text-primary': '#0F172A',
                '--text-secondary': '#475569',
                '--text-muted': '#64748b',
                '--text-white': '#ffffff',
                '--accent': '#3b82f6',
                '--accent-hover': '#2563eb',
                '--border-color': '#e2e8f0',
                '--sidebar-hover': '#e2e8f0',
                '--scrollbar-thumb': '#cbd5e1',
                '--bg-editor': '#ffffff',
                '--text-editor-code': '#0F172A',
                '--wallpaper-opacity': '0.05',
                '--wallpaper-brightness': '0.9',
                '--text-success': '#16a34a',
                '--text-error': '#dc2626',
                '--text-warning': '#d97706',
                '--text-info': '#2563eb',
                '--text-purple': '#7c3aed',
                '--text-orange': '#ea580c',
                '--text-cyan': '#0891b2'
            }
        }
    },
    icons: commonIcons
};
